apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: stephengrider/multi-server
          ports:
            - containerPort: 5000
          env:
            # For the first two, check multi-worker
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            # Default name we defined before
            - name: PGUSER
              value: postgres
            # Host (name) defined in postgres-cluster-ip-service
            - name: PGHOST
              value: postgres-cluster-ip-service
            # Default Postgres port
            - name: PGPORT
              value: '5432'
            # Default Postgres database
            - name: PGDATABASE
              value: postgres
            # Adding our Secret as Env Var.
            # Notice that we configure the name
            # of the secret, and then in "key"
            # reference the key of the key-value pair
            # that we defined in the secret (remember 
            # that it can contain many key-value pairs)
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD